#spring.datasource.url = jdbc:mysql://localhost:3306/myscoremanage?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username = root
#spring.datasource.password = 19970806
#
#server.port=8080
#
#spring.thymeleaf.cache=false
#spring.thymeleaf.mode=LEGACYHTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.servlet.content-type=text/html

spring :
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms_v1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://111.229.118.243:3306/cms_v1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 19970806

  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:   #静态文件
    static-path-pattern : /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml


