package com.wayne.sms.dao;

import com.wayne.sms.pojo.College;
import com.wayne.sms.pojo.CollegeExample;
import com.wayne.sms.pojo.CollegeKey;
import java.util.List;

public interface CollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int deleteByPrimaryKey(CollegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    List<College> selectByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    College selectByPrimaryKey(CollegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int updateByPrimaryKeySelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int updateByPrimaryKey(College record);

    College selectByCollegeId(Integer collegeId);

}