package com.wayne.sms.dao;

import com.wayne.sms.pojo.MajorCourseExample;
import com.wayne.sms.pojo.MajorCourseKey;
import java.util.List;

public interface MajorCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int deleteByPrimaryKey(MajorCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int insert(MajorCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int insertSelective(MajorCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    List<MajorCourseKey> selectByExample(MajorCourseExample example);
}