package com.wayne.sms.dao;

import com.wayne.sms.pojo.*;

import java.util.List;

public interface MathScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    int insert(MathScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    int insertSelective(MathScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    List<MathScore> selectByExample(MathScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    MathScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    int updateByPrimaryKeySelective(MathScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_math_score
     *
     * @mbggenerated Sat Mar 28 13:13:30 CST 2020
     */
    int updateByPrimaryKey(MathScore record);

    int deleteByExample(MathScoreExample example);


    List<SaCollege> selectAsSaCollege();


    List<SaMajor> selectAsSaMajor();

    List<SaClazz> selectAsSaClazz();

    List<SaStudent> selectAsSaStudent();

}