package com.wayne.sms.dao;

import com.wayne.sms.pojo.SaClazz;
import com.wayne.sms.pojo.SaClazzExample;
import com.wayne.sms.pojo.StdClazz;

import java.util.List;

public interface SaClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int insert(SaClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int insertSelective(SaClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    List<SaClazz> selectByExample(SaClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    SaClazz selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int updateByPrimaryKeySelective(SaClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_clazz
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int updateByPrimaryKey(SaClazz record);

    void truncateTable();

    int insertIntoSaClazz(List<SaClazz> saClazzes);

    List<StdClazz> selectAsSTDClazzes();

    int updateStdScore();
}