package com.wayne.sms.dao;

import com.wayne.sms.pojo.SaCollege;
import com.wayne.sms.pojo.SaCollegeExample;
import java.util.List;

public interface SaCollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    int insert(SaCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    int insertSelective(SaCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    List<SaCollege> selectByExample(SaCollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    SaCollege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    int updateByPrimaryKeySelective(SaCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_college
     *
     * @mbggenerated Thu Apr 02 10:51:13 CST 2020
     */
    int updateByPrimaryKey(SaCollege record);

    void truncateSaCollege();

    int insertIntoSaCollege(List<SaCollege> saColleges);
}