package com.wayne.sms.dao;

import com.wayne.sms.pojo.SaMajor;
import com.wayne.sms.pojo.SaMajorExample;
import com.wayne.sms.pojo.StdMajor;

import java.util.List;

public interface SaMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int insert(SaMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int insertSelective(SaMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    List<SaMajor> selectByExample(SaMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    SaMajor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int updateByPrimaryKeySelective(SaMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    int updateByPrimaryKey(SaMajor record);

    void truncateSaMajor();

    int insertIntoSaMajor(List<SaMajor> saMajors);

    List<StdMajor> selectAsStdMajor();

    int updateStdScore();
}