package com.wayne.sms.dao;

import com.wayne.sms.pojo.SaStudent;
import com.wayne.sms.pojo.SaStudentExample;
import com.wayne.sms.pojo.StdStudent;

import java.util.List;

public interface SaStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    int insert(SaStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    int insertSelective(SaStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    List<SaStudent> selectByExample(SaStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    SaStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    int updateByPrimaryKeySelective(SaStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    int updateByPrimaryKey(SaStudent record);

    void truncateTable();

    int insertIntoSaStudents(List<SaStudent> saStudents);

    List<StdStudent> selectAsStdStudents();

    int updateStdScore();

}