package com.wayne.sms.dao;

import com.wayne.sms.pojo.StdClazz;
import com.wayne.sms.pojo.StdClazzExample;
import java.util.List;

public interface StdClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_std_clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    int insert(StdClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_std_clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    int insertSelective(StdClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_std_clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    List<StdClazz> selectByExample(StdClazzExample example);

    int insertIntoStdClazz(List<StdClazz> stdClazzes);

    void clearTable();

}