package com.wayne.sms.dao;

import com.wayne.sms.pojo.StdStudent;
import com.wayne.sms.pojo.StdStudentExample;
import java.util.List;

public interface StdStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_std_student
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    int insert(StdStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_std_student
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    int insertSelective(StdStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_std_student
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    List<StdStudent> selectByExample(StdStudentExample example);

    void clearTable();

    int insertIntoStdStudent(List<StdStudent> stdStudents);

}