package com.wayne.sms.dao;

import com.wayne.sms.pojo.TeacherCourse;
import com.wayne.sms.pojo.TeacherCourseExample;
import java.util.List;

public interface TeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    int deleteByPrimaryKey(Long teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    int insert(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    int insertSelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    List<TeacherCourse> selectByExample(TeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    TeacherCourse selectByPrimaryKey(Long teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    int updateByPrimaryKeySelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Wed Apr 15 16:15:43 CST 2020
     */
    int updateByPrimaryKey(TeacherCourse record);
}