package com.wayne.sms.dao;

import com.wayne.sms.pojo.TeacherCourseExample;
import com.wayne.sms.pojo.TeacherCourseKey;
import java.util.List;

public interface TeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int deleteByPrimaryKey(TeacherCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int insert(TeacherCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    int insertSelective(TeacherCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    List<TeacherCourseKey> selectByExample(TeacherCourseExample example);
}