package com.wayne.sms.pojo;

import java.io.Serializable;

public class ClazzKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clazz.clazz_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clazz.clazz_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String clazzName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_clazz
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clazz.clazz_id
     *
     * @return the value of t_clazz.clazz_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clazz.clazz_id
     *
     * @param clazzId the value for t_clazz.clazz_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clazz.clazz_name
     *
     * @return the value of t_clazz.clazz_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clazz.clazz_name
     *
     * @param clazzName the value for t_clazz.clazz_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    @Override
    public String toString() {
        return "ClazzKey{" +
                "clazzId=" + clazzId +
                ", clazzName='" + clazzName + '\'' +
                '}';
    }
}