package com.wayne.sms.pojo;

import java.io.Serializable;

public class Course implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_id
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_name
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.couse_info
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    private String couseInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.regular_score_per
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    private Double regularScorePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.final_score_per
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    private Double finalScorePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_course
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_id
     *
     * @return the value of t_course.course_id
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_id
     *
     * @param courseId the value for t_course.course_id
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_name
     *
     * @return the value of t_course.course_name
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_name
     *
     * @param courseName the value for t_course.course_name
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.couse_info
     *
     * @return the value of t_course.couse_info
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public String getCouseInfo() {
        return couseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.couse_info
     *
     * @param couseInfo the value for t_course.couse_info
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public void setCouseInfo(String couseInfo) {
        this.couseInfo = couseInfo == null ? null : couseInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.regular_score_per
     *
     * @return the value of t_course.regular_score_per
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public Double getRegularScorePer() {
        return regularScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.regular_score_per
     *
     * @param regularScorePer the value for t_course.regular_score_per
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public void setRegularScorePer(Double regularScorePer) {
        this.regularScorePer = regularScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.final_score_per
     *
     * @return the value of t_course.final_score_per
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public Double getFinalScorePer() {
        return finalScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.final_score_per
     *
     * @param finalScorePer the value for t_course.final_score_per
     *
     * @mbggenerated Sat Apr 18 23:36:53 CST 2020
     */
    public void setFinalScorePer(Double finalScorePer) {
        this.finalScorePer = finalScorePer;
    }
}