package com.wayne.sms.pojo;

import java.io.Serializable;

public class CourseKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_id
     *
     * @return the value of t_course.course_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_id
     *
     * @param courseId the value for t_course.course_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_name
     *
     * @return the value of t_course.course_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_name
     *
     * @param courseName the value for t_course.course_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }
}