package com.wayne.sms.pojo;

import java.io.Serializable;

public class Course extends CourseKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.couse_info
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String couseInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.couse_info
     *
     * @return the value of t_course.couse_info
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getCouseInfo() {
        return couseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.couse_info
     *
     * @param couseInfo the value for t_course.couse_info
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setCouseInfo(String couseInfo) {
        this.couseInfo = couseInfo == null ? null : couseInfo.trim();
    }


}