package com.wayne.sms.pojo;

import java.io.Serializable;

public class Major extends MajorKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.college_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_major
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.college_id
     *
     * @return the value of t_major.college_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.college_id
     *
     * @param collegeId the value for t_major.college_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    @Override
    public String toString() {
        return "Major{" +
                "collegeId=" + collegeId +super.toString()+
                '}';
    }
}