package com.wayne.sms.pojo;

import java.io.Serializable;

public class MajorKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.major_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.major_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String majorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_major
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.major_id
     *
     * @return the value of t_major.major_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.major_id
     *
     * @param majorId the value for t_major.major_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.major_name
     *
     * @return the value of t_major.major_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.major_name
     *
     * @param majorName the value for t_major.major_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }


    @Override
    public String toString() {
        return "MajorKey{" +
                "majorId=" + majorId +
                ", majorName='" + majorName + '\'' +
                '}';
    }
}