package com.wayne.sms.pojo;

import java.io.Serializable;

public class MajorCourseKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major_course.course_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major_course.major_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_major_course
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major_course.course_id
     *
     * @return the value of t_major_course.course_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major_course.course_id
     *
     * @param courseId the value for t_major_course.course_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major_course.major_id
     *
     * @return the value of t_major_course.major_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major_course.major_id
     *
     * @param majorId the value for t_major_course.major_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }
}