package com.wayne.sms.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SaMajorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public SaMajorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNull() {
            addCriterion("course_name is null");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNotNull() {
            addCriterion("course_name is not null");
            return (Criteria) this;
        }

        public Criteria andCourseNameEqualTo(String value) {
            addCriterion("course_name =", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotEqualTo(String value) {
            addCriterion("course_name <>", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThan(String value) {
            addCriterion("course_name >", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThanOrEqualTo(String value) {
            addCriterion("course_name >=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThan(String value) {
            addCriterion("course_name <", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThanOrEqualTo(String value) {
            addCriterion("course_name <=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLike(String value) {
            addCriterion("course_name like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotLike(String value) {
            addCriterion("course_name not like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameIn(List<String> values) {
            addCriterion("course_name in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotIn(List<String> values) {
            addCriterion("course_name not in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameBetween(String value1, String value2) {
            addCriterion("course_name between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotBetween(String value1, String value2) {
            addCriterion("course_name not between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNull() {
            addCriterion("college is null");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNotNull() {
            addCriterion("college is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeEqualTo(String value) {
            addCriterion("college =", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotEqualTo(String value) {
            addCriterion("college <>", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThan(String value) {
            addCriterion("college >", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("college >=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThan(String value) {
            addCriterion("college <", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThanOrEqualTo(String value) {
            addCriterion("college <=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLike(String value) {
            addCriterion("college like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotLike(String value) {
            addCriterion("college not like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeIn(List<String> values) {
            addCriterion("college in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotIn(List<String> values) {
            addCriterion("college not in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeBetween(String value1, String value2) {
            addCriterion("college between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotBetween(String value1, String value2) {
            addCriterion("college not between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andMajorIsNull() {
            addCriterion("major is null");
            return (Criteria) this;
        }

        public Criteria andMajorIsNotNull() {
            addCriterion("major is not null");
            return (Criteria) this;
        }

        public Criteria andMajorEqualTo(String value) {
            addCriterion("major =", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotEqualTo(String value) {
            addCriterion("major <>", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThan(String value) {
            addCriterion("major >", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThanOrEqualTo(String value) {
            addCriterion("major >=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThan(String value) {
            addCriterion("major <", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThanOrEqualTo(String value) {
            addCriterion("major <=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLike(String value) {
            addCriterion("major like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotLike(String value) {
            addCriterion("major not like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorIn(List<String> values) {
            addCriterion("major in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotIn(List<String> values) {
            addCriterion("major not in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorBetween(String value1, String value2) {
            addCriterion("major between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotBetween(String value1, String value2) {
            addCriterion("major not between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreIsNull() {
            addCriterion("avg_regular_score is null");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreIsNotNull() {
            addCriterion("avg_regular_score is not null");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreEqualTo(BigDecimal value) {
            addCriterion("avg_regular_score =", value, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreNotEqualTo(BigDecimal value) {
            addCriterion("avg_regular_score <>", value, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreGreaterThan(BigDecimal value) {
            addCriterion("avg_regular_score >", value, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_regular_score >=", value, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreLessThan(BigDecimal value) {
            addCriterion("avg_regular_score <", value, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_regular_score <=", value, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreIn(List<BigDecimal> values) {
            addCriterion("avg_regular_score in", values, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreNotIn(List<BigDecimal> values) {
            addCriterion("avg_regular_score not in", values, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_regular_score between", value1, value2, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgRegularScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_regular_score not between", value1, value2, "avgRegularScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreIsNull() {
            addCriterion("avg_final_score is null");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreIsNotNull() {
            addCriterion("avg_final_score is not null");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreEqualTo(BigDecimal value) {
            addCriterion("avg_final_score =", value, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreNotEqualTo(BigDecimal value) {
            addCriterion("avg_final_score <>", value, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreGreaterThan(BigDecimal value) {
            addCriterion("avg_final_score >", value, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_final_score >=", value, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreLessThan(BigDecimal value) {
            addCriterion("avg_final_score <", value, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_final_score <=", value, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreIn(List<BigDecimal> values) {
            addCriterion("avg_final_score in", values, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreNotIn(List<BigDecimal> values) {
            addCriterion("avg_final_score not in", values, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_final_score between", value1, value2, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgFinalScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_final_score not between", value1, value2, "avgFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreIsNull() {
            addCriterion("std_final_score is null");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreIsNotNull() {
            addCriterion("std_final_score is not null");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreEqualTo(BigDecimal value) {
            addCriterion("std_final_score =", value, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreNotEqualTo(BigDecimal value) {
            addCriterion("std_final_score <>", value, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreGreaterThan(BigDecimal value) {
            addCriterion("std_final_score >", value, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("std_final_score >=", value, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreLessThan(BigDecimal value) {
            addCriterion("std_final_score <", value, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("std_final_score <=", value, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreIn(List<BigDecimal> values) {
            addCriterion("std_final_score in", values, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreNotIn(List<BigDecimal> values) {
            addCriterion("std_final_score not in", values, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_final_score between", value1, value2, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andStdFinalScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_final_score not between", value1, value2, "stdFinalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreIsNull() {
            addCriterion("avg_total_score is null");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreIsNotNull() {
            addCriterion("avg_total_score is not null");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreEqualTo(BigDecimal value) {
            addCriterion("avg_total_score =", value, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreNotEqualTo(BigDecimal value) {
            addCriterion("avg_total_score <>", value, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreGreaterThan(BigDecimal value) {
            addCriterion("avg_total_score >", value, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_total_score >=", value, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreLessThan(BigDecimal value) {
            addCriterion("avg_total_score <", value, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_total_score <=", value, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreIn(List<BigDecimal> values) {
            addCriterion("avg_total_score in", values, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreNotIn(List<BigDecimal> values) {
            addCriterion("avg_total_score not in", values, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_total_score between", value1, value2, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andAvgTotalScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_total_score not between", value1, value2, "avgTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreIsNull() {
            addCriterion("std_total_score is null");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreIsNotNull() {
            addCriterion("std_total_score is not null");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreEqualTo(BigDecimal value) {
            addCriterion("std_total_score =", value, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreNotEqualTo(BigDecimal value) {
            addCriterion("std_total_score <>", value, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreGreaterThan(BigDecimal value) {
            addCriterion("std_total_score >", value, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("std_total_score >=", value, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreLessThan(BigDecimal value) {
            addCriterion("std_total_score <", value, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("std_total_score <=", value, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreIn(List<BigDecimal> values) {
            addCriterion("std_total_score in", values, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreNotIn(List<BigDecimal> values) {
            addCriterion("std_total_score not in", values, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_total_score between", value1, value2, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andStdTotalScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_total_score not between", value1, value2, "stdTotalScore");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuIsNull() {
            addCriterion("sum_major_stu is null");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuIsNotNull() {
            addCriterion("sum_major_stu is not null");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuEqualTo(Long value) {
            addCriterion("sum_major_stu =", value, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuNotEqualTo(Long value) {
            addCriterion("sum_major_stu <>", value, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuGreaterThan(Long value) {
            addCriterion("sum_major_stu >", value, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_major_stu >=", value, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuLessThan(Long value) {
            addCriterion("sum_major_stu <", value, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuLessThanOrEqualTo(Long value) {
            addCriterion("sum_major_stu <=", value, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuIn(List<Long> values) {
            addCriterion("sum_major_stu in", values, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuNotIn(List<Long> values) {
            addCriterion("sum_major_stu not in", values, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuBetween(Long value1, Long value2) {
            addCriterion("sum_major_stu between", value1, value2, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumMajorStuNotBetween(Long value1, Long value2) {
            addCriterion("sum_major_stu not between", value1, value2, "sumMajorStu");
            return (Criteria) this;
        }

        public Criteria andSumExcellentIsNull() {
            addCriterion("sum_excellent is null");
            return (Criteria) this;
        }

        public Criteria andSumExcellentIsNotNull() {
            addCriterion("sum_excellent is not null");
            return (Criteria) this;
        }

        public Criteria andSumExcellentEqualTo(Long value) {
            addCriterion("sum_excellent =", value, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentNotEqualTo(Long value) {
            addCriterion("sum_excellent <>", value, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentGreaterThan(Long value) {
            addCriterion("sum_excellent >", value, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_excellent >=", value, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentLessThan(Long value) {
            addCriterion("sum_excellent <", value, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentLessThanOrEqualTo(Long value) {
            addCriterion("sum_excellent <=", value, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentIn(List<Long> values) {
            addCriterion("sum_excellent in", values, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentNotIn(List<Long> values) {
            addCriterion("sum_excellent not in", values, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentBetween(Long value1, Long value2) {
            addCriterion("sum_excellent between", value1, value2, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumExcellentNotBetween(Long value1, Long value2) {
            addCriterion("sum_excellent not between", value1, value2, "sumExcellent");
            return (Criteria) this;
        }

        public Criteria andSumGoodIsNull() {
            addCriterion("sum_good is null");
            return (Criteria) this;
        }

        public Criteria andSumGoodIsNotNull() {
            addCriterion("sum_good is not null");
            return (Criteria) this;
        }

        public Criteria andSumGoodEqualTo(Long value) {
            addCriterion("sum_good =", value, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodNotEqualTo(Long value) {
            addCriterion("sum_good <>", value, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodGreaterThan(Long value) {
            addCriterion("sum_good >", value, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_good >=", value, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodLessThan(Long value) {
            addCriterion("sum_good <", value, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodLessThanOrEqualTo(Long value) {
            addCriterion("sum_good <=", value, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodIn(List<Long> values) {
            addCriterion("sum_good in", values, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodNotIn(List<Long> values) {
            addCriterion("sum_good not in", values, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodBetween(Long value1, Long value2) {
            addCriterion("sum_good between", value1, value2, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumGoodNotBetween(Long value1, Long value2) {
            addCriterion("sum_good not between", value1, value2, "sumGood");
            return (Criteria) this;
        }

        public Criteria andSumMediumIsNull() {
            addCriterion("sum_medium is null");
            return (Criteria) this;
        }

        public Criteria andSumMediumIsNotNull() {
            addCriterion("sum_medium is not null");
            return (Criteria) this;
        }

        public Criteria andSumMediumEqualTo(Long value) {
            addCriterion("sum_medium =", value, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumNotEqualTo(Long value) {
            addCriterion("sum_medium <>", value, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumGreaterThan(Long value) {
            addCriterion("sum_medium >", value, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_medium >=", value, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumLessThan(Long value) {
            addCriterion("sum_medium <", value, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumLessThanOrEqualTo(Long value) {
            addCriterion("sum_medium <=", value, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumIn(List<Long> values) {
            addCriterion("sum_medium in", values, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumNotIn(List<Long> values) {
            addCriterion("sum_medium not in", values, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumBetween(Long value1, Long value2) {
            addCriterion("sum_medium between", value1, value2, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumMediumNotBetween(Long value1, Long value2) {
            addCriterion("sum_medium not between", value1, value2, "sumMedium");
            return (Criteria) this;
        }

        public Criteria andSumPassIsNull() {
            addCriterion("sum_pass is null");
            return (Criteria) this;
        }

        public Criteria andSumPassIsNotNull() {
            addCriterion("sum_pass is not null");
            return (Criteria) this;
        }

        public Criteria andSumPassEqualTo(Long value) {
            addCriterion("sum_pass =", value, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassNotEqualTo(Long value) {
            addCriterion("sum_pass <>", value, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassGreaterThan(Long value) {
            addCriterion("sum_pass >", value, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_pass >=", value, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassLessThan(Long value) {
            addCriterion("sum_pass <", value, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassLessThanOrEqualTo(Long value) {
            addCriterion("sum_pass <=", value, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassIn(List<Long> values) {
            addCriterion("sum_pass in", values, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassNotIn(List<Long> values) {
            addCriterion("sum_pass not in", values, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassBetween(Long value1, Long value2) {
            addCriterion("sum_pass between", value1, value2, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumPassNotBetween(Long value1, Long value2) {
            addCriterion("sum_pass not between", value1, value2, "sumPass");
            return (Criteria) this;
        }

        public Criteria andSumFailIsNull() {
            addCriterion("sum_fail is null");
            return (Criteria) this;
        }

        public Criteria andSumFailIsNotNull() {
            addCriterion("sum_fail is not null");
            return (Criteria) this;
        }

        public Criteria andSumFailEqualTo(Long value) {
            addCriterion("sum_fail =", value, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailNotEqualTo(Long value) {
            addCriterion("sum_fail <>", value, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailGreaterThan(Long value) {
            addCriterion("sum_fail >", value, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_fail >=", value, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailLessThan(Long value) {
            addCriterion("sum_fail <", value, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailLessThanOrEqualTo(Long value) {
            addCriterion("sum_fail <=", value, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailIn(List<Long> values) {
            addCriterion("sum_fail in", values, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailNotIn(List<Long> values) {
            addCriterion("sum_fail not in", values, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailBetween(Long value1, Long value2) {
            addCriterion("sum_fail between", value1, value2, "sumFail");
            return (Criteria) this;
        }

        public Criteria andSumFailNotBetween(Long value1, Long value2) {
            addCriterion("sum_fail not between", value1, value2, "sumFail");
            return (Criteria) this;
        }

        public Criteria andStdScoreIsNull() {
            addCriterion("std_score is null");
            return (Criteria) this;
        }

        public Criteria andStdScoreIsNotNull() {
            addCriterion("std_score is not null");
            return (Criteria) this;
        }

        public Criteria andStdScoreEqualTo(BigDecimal value) {
            addCriterion("std_score =", value, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreNotEqualTo(BigDecimal value) {
            addCriterion("std_score <>", value, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreGreaterThan(BigDecimal value) {
            addCriterion("std_score >", value, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("std_score >=", value, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreLessThan(BigDecimal value) {
            addCriterion("std_score <", value, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("std_score <=", value, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreIn(List<BigDecimal> values) {
            addCriterion("std_score in", values, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreNotIn(List<BigDecimal> values) {
            addCriterion("std_score not in", values, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_score between", value1, value2, "stdScore");
            return (Criteria) this;
        }

        public Criteria andStdScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_score not between", value1, value2, "stdScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sa_major
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 03 14:01:01 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sa_major
     *
     * @mbggenerated Fri Apr 03 14:01:01 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}