package com.wayne.sms.pojo;

import java.io.Serializable;

public class SaStudent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.id
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.stu_id
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Long stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.stu_name
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.college
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.major
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.clazz
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.grade
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.course_name
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.regular_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double regularScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.regular_score_per
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double regularScorePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.final_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double finalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.final_score_per
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double finalScorePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.total_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.gpa
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double gpa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sa_student.std_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private Double stdScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sa_student
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.id
     *
     * @return the value of t_sa_student.id
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.id
     *
     * @param id the value for t_sa_student.id
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.stu_id
     *
     * @return the value of t_sa_student.stu_id
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.stu_id
     *
     * @param stuId the value for t_sa_student.stu_id
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.stu_name
     *
     * @return the value of t_sa_student.stu_name
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.stu_name
     *
     * @param stuName the value for t_sa_student.stu_name
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.college
     *
     * @return the value of t_sa_student.college
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.college
     *
     * @param college the value for t_sa_student.college
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.major
     *
     * @return the value of t_sa_student.major
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.major
     *
     * @param major the value for t_sa_student.major
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.clazz
     *
     * @return the value of t_sa_student.clazz
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.clazz
     *
     * @param clazz the value for t_sa_student.clazz
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.grade
     *
     * @return the value of t_sa_student.grade
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.grade
     *
     * @param grade the value for t_sa_student.grade
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.course_name
     *
     * @return the value of t_sa_student.course_name
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.course_name
     *
     * @param courseName the value for t_sa_student.course_name
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.regular_score
     *
     * @return the value of t_sa_student.regular_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getRegularScore() {
        return regularScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.regular_score
     *
     * @param regularScore the value for t_sa_student.regular_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setRegularScore(Double regularScore) {
        this.regularScore = regularScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.regular_score_per
     *
     * @return the value of t_sa_student.regular_score_per
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getRegularScorePer() {
        return regularScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.regular_score_per
     *
     * @param regularScorePer the value for t_sa_student.regular_score_per
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setRegularScorePer(Double regularScorePer) {
        this.regularScorePer = regularScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.final_score
     *
     * @return the value of t_sa_student.final_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getFinalScore() {
        return finalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.final_score
     *
     * @param finalScore the value for t_sa_student.final_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setFinalScore(Double finalScore) {
        this.finalScore = finalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.final_score_per
     *
     * @return the value of t_sa_student.final_score_per
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getFinalScorePer() {
        return finalScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.final_score_per
     *
     * @param finalScorePer the value for t_sa_student.final_score_per
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setFinalScorePer(Double finalScorePer) {
        this.finalScorePer = finalScorePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.total_score
     *
     * @return the value of t_sa_student.total_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.total_score
     *
     * @param totalScore the value for t_sa_student.total_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setTotalScore(Double totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.gpa
     *
     * @return the value of t_sa_student.gpa
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getGpa() {
        return gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.gpa
     *
     * @param gpa the value for t_sa_student.gpa
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setGpa(Double gpa) {
        this.gpa = gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sa_student.std_score
     *
     * @return the value of t_sa_student.std_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public Double getStdScore() {
        return stdScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sa_student.std_score
     *
     * @param stdScore the value for t_sa_student.std_score
     *
     * @mbggenerated Tue Mar 31 22:43:42 CST 2020
     */
    public void setStdScore(Double stdScore) {
        this.stdScore = stdScore;
    }

    @Override
    public String toString() {
        return "SaStudent{" +
                "id=" + id +
                ", stuId=" + stuId +
                ", stuName='" + stuName + '\'' +
                ", college='" + college + '\'' +
                ", major='" + major + '\'' +
                ", clazz='" + clazz + '\'' +
                ", grade=" + grade +
                ", courseName='" + courseName + '\'' +
                ", regularScore=" + regularScore +
                ", regularScorePer=" + regularScorePer +
                ", finalScore=" + finalScore +
                ", finalScorePer=" + finalScorePer +
                ", totalScore=" + totalScore +
                ", gpa=" + gpa +
                ", stdScore=" + stdScore +
                '}';
    }
}