package com.wayne.sms.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class StdClazz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_clazz.major
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_clazz.clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_clazz.course_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_clazz.std_score
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private BigDecimal stdScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_std_clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_clazz.major
     *
     * @return the value of t_std_clazz.major
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_clazz.major
     *
     * @param major the value for t_std_clazz.major
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_clazz.clazz
     *
     * @return the value of t_std_clazz.clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_clazz.clazz
     *
     * @param clazz the value for t_std_clazz.clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_clazz.course_name
     *
     * @return the value of t_std_clazz.course_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_clazz.course_name
     *
     * @param courseName the value for t_std_clazz.course_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_clazz.std_score
     *
     * @return the value of t_std_clazz.std_score
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public BigDecimal getStdScore() {
        return stdScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_clazz.std_score
     *
     * @param stdScore the value for t_std_clazz.std_score
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setStdScore(BigDecimal stdScore) {
        this.stdScore = stdScore;
    }
}