package com.wayne.sms.pojo;

import java.io.Serializable;

public class StdStudent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_student.clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_student.stu_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_student.course_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_std_student.std_score
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private Double stdScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_std_student
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_student.clazz
     *
     * @return the value of t_std_student.clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_student.clazz
     *
     * @param clazz the value for t_std_student.clazz
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_student.stu_name
     *
     * @return the value of t_std_student.stu_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_student.stu_name
     *
     * @param stuName the value for t_std_student.stu_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_student.course_name
     *
     * @return the value of t_std_student.course_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_student.course_name
     *
     * @param courseName the value for t_std_student.course_name
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_std_student.std_score
     *
     * @return the value of t_std_student.std_score
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public Double getStdScore() {
        return stdScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_std_student.std_score
     *
     * @param stdScore the value for t_std_student.std_score
     *
     * @mbggenerated Fri Apr 03 15:41:56 CST 2020
     */
    public void setStdScore(Double stdScore) {
        this.stdScore = stdScore;
    }


    @Override
    public String toString() {
        return "StdStudent{" +
                "clazz='" + clazz + '\'' +
                ", stuName='" + stuName + '\'' +
                ", courseName='" + courseName + '\'' +
                ", stdScore=" + stdScore +
                '}';
    }
}