package com.wayne.sms.pojo;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Long stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.grade
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.major
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.clazz
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_id
     *
     * @return the value of t_student.stu_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_id
     *
     * @param stuId the value for t_student.stu_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.grade
     *
     * @return the value of t_student.grade
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.grade
     *
     * @param grade the value for t_student.grade
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.college
     *
     * @return the value of t_student.college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.college
     *
     * @param college the value for t_student.college
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.major
     *
     * @return the value of t_student.major
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.major
     *
     * @param major the value for t_student.major
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.clazz
     *
     * @return the value of t_student.clazz
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.clazz
     *
     * @param clazz the value for t_student.clazz
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    @Override
    public String toString() {
        return "Student{" +
                "stuId=" + stuId +
                ", name='" + name + '\'' +
                ", grade=" + grade +
                ", college='" + college + '\'' +
                ", major='" + major + '\'' +
                ", clazz='" + clazz + '\'' +
                '}';
    }
}