package com.wayne.sms.pojo;

import java.io.Serializable;

public class Teacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_id
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.name
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.job
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.college_name
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    private String collegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_teacher
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_id
     *
     * @return the value of t_teacher.teacher_id
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_id
     *
     * @param teacherId the value for t_teacher.teacher_id
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.name
     *
     * @return the value of t_teacher.name
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.name
     *
     * @param name the value for t_teacher.name
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.job
     *
     * @return the value of t_teacher.job
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.job
     *
     * @param job the value for t_teacher.job
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.college_name
     *
     * @return the value of t_teacher.college_name
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.college_name
     *
     * @param collegeName the value for t_teacher.college_name
     *
     * @mbggenerated Mon Apr 06 14:51:38 CST 2020
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }
}