package com.wayne.sms.pojo;

import java.io.Serializable;

public class Userlogin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userlogin.user_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userlogin.user_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userlogin.password
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userlogin.role
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private Integer role;

    private String roleName;

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_userlogin
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userlogin.user_id
     *
     * @return the value of t_userlogin.user_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userlogin.user_id
     *
     * @param userId the value for t_userlogin.user_id
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userlogin.user_name
     *
     * @return the value of t_userlogin.user_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userlogin.user_name
     *
     * @param userName the value for t_userlogin.user_name
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userlogin.password
     *
     * @return the value of t_userlogin.password
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userlogin.password
     *
     * @param password the value for t_userlogin.password
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userlogin.role
     *
     * @return the value of t_userlogin.role
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userlogin.role
     *
     * @param role the value for t_userlogin.role
     *
     * @mbggenerated Mon Mar 16 14:52:57 CST 2020
     */
    public void setRole(Integer role) {
        this.role = role;
    }


    @Override
    public String toString() {
        return "Userlogin{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", role=" + role +
                ", roleName='" + roleName + '\'' +
                '}';
    }
}